repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-vcs-permalinks
  - id: mixed-line-ending
  - id: check-yaml
  - id: check-json

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
